### ISSUE TITLE
Not saving in .mp3 format

### ISSUE THREAD

**Issue by massens** [pacso/paperclip-wav-mp3#1]
Hi, first of all, thank you very much for this very nice gem!

When I use your processor, the file is converted to .mp3, but is saved with the same file name ('file_name.wav').  So the new file is encoded in .mp3 but in the extension name ways .wav. Do you know how to save it with the new extension in the file name?

Thanks,
Marc

**Comment by pacso** [comment]
Hi Marc,

When you use paperclip for attaching files to a model, the original uploaded file is never altered. So when uploading your .wav file that will be stored unaltered. When the processor is used to convert this to an .mp3, this is then stored in another folder. You should have two files stored after uploading your .wav file.

If this isn't the case, you may not have the processor running correctly. Can you check you have all of the prerequisites installed and working?

Feel free to post a snippet of your model if you want me to check you've got everything set up correctly there.
